language: cpp
compiler:
  - gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9


install:
  # ==== install the newest cmake ====
  # https://riptutorial.com/ja/cmake/example/4723/%E6%9C%80%E6%96%B0%E3%81%AEcmake%E3%81%A7travis-ci%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B
  #  (v3.3 -> v3.18 へ変更)
  # first we create a directory for the CMake binaries
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.18/cmake-3.18.0-rc3-Linux-x86_64.tar.gz
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - tar -xvf cmake-3.18.0-rc3-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.18.0-rc3-Linux-x86_64 cmake-install
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # don't forget to switch back to the main build directory once you are done
  - cd ${TRAVIS_BUILD_DIR}

  # ==== install gtest ====
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  # sudo 時にもとの環境変数 PATH を引き継ぐ必要がある (これをしないと cmake not found と怒られる)
  - sudo env "PATH=$PATH" cmake .
  - sudo env "PATH=$PATH" cmake --build .
  - sudo mv libg* /usr/local/lib/
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  # use new gcc, g++
  - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  - gcc -v && g++ -v && cmake --version && ctest --version

script:
  - mkdir build
  - cd build && cmake .. && make
  - ctest -V
